### ISSUE TITLE
Encapsulation issue with Exam class

### ISSUE THREAD

**Issue by cervonwong** [appventure-nush/exam-clock-2020#11]
Instance fields `id`, `name`, `date`, `start`, `end`, are public variables. I assume this related to the JSON conversion empty constructor where fields are initialised by setting the variables directly. But I do not think that using public variables as getters and setters is common convention.

There are getters for these fields but I cannot find any instance of them being used in the code.

Suggestion:
Create a builder/model class with the public variables for GSON, then convert the builder/model class to the normal Exam class, then switch all references in code of the public variables (e.g. in `ExamHolder` and `MainController`) to use the getters instead.

If the getters are not inteneded to be used, maybe comment them out to reduce confusion?

**Comment by octo-kumo** [comment]
noted, will look into that
