### ISSUE TITLE
Methods in exam not being used when appropriate

### ISSUE THREAD

**Issue by cervonwong** [appventure-nush/exam-clock-2020#12]
`Exam`'s constructor accepts a `LocalTime` for `start` and `end` parameters, then converts them into `String`s in `start` and `end` fields. Methods which want to get the start and end times of exams, e.g. in `ExamHolder.java`, then converts it back to a `LocalTime`, but it does not use the convenient `getStartTimeObj()` and `getEndTimeObj()` provided by the `Exam` class, instead getting the `String` fields and parsing it to a `LocalTime` itself. 

Is there any rationale for this double conversion from `LocalTime` to `String` then back to `LocalTime`, 

and is there any rationale for not using `getStartTimeObj()` and `getEndTimeObj()` in lines 221 and 222 of `ExamHolder.java`?

Thanks! 👍🏻

**Comment by octo-kumo** [comment]
The reason for using string in the object is because JSON library I am using right now does not support LocalDate or LocalTime

I will look into it

**Comment by octo-kumo** [comment]
somehow chaining `fix` does not work
