### ISSUE TITLE
[Feature] A bunch of UI suggestions to consider

### ISSUE THREAD

**Issue by cervonwong** [appventure-nush/exam-clock-2020#14]
1. Show an 'Add exam' button on the right panel in the center when there are no exams, or below the last exam when there are exams. I think 'Add exam' would be the most common action performed in the app so it will be easier to use the app if an 'Add exam' button can be found instantly on the right panel.

1. Use something in addition to color to show whether the toilet is occupied or not. Colourblind students might not be able to tell the difference between red and green.

1. Clock ID in connection tab is not selectable and copyable.

1. Digital clock's color in light mode might be hard to see for students with slight visual impairments. See the colors when a grayscale filter is applied:
![image](https://user-images.githubusercontent.com/44718681/102629707-73d9aa80-4186-11eb-84f0-70eb66b4c6a0.png)
Perhaps lightening the background of the digital clock and darkening the digits of the digital clock would make it easier to read.

The app looks good so far from the initial screen, hope to see it being used when it exits beta. :)

**Comment by octo-kumo** [comment]
idk about the colour blind part, not like I can just hide the icon,
maybe switch between fill / outline?

**Comment by cervonwong** [comment]
I was thinking maybe putting some text "OPEN" / "IN USE" like public restrooms, or drawing a large cross 'X' over the icons when the toilets are not in use.

**Comment by octo-kumo** [comment]
I think I will either draw **O**/**X** over the icons or use outline when occupied

**Comment by octo-kumo** [comment]
<img width="852" alt="Screenshot 2020-12-19 at 6 33 17 PM" src="https://user-images.githubusercontent.com/26460801/102686109-c075c200-4228-11eb-9569-d10d2ad5decd.png">
<img width="852" alt="Screenshot 2020-12-19 at 6 33 06 PM" src="https://user-images.githubusercontent.com/26460801/102686111-c5d30c80-4228-11eb-8d34-661aeb378bcd.png">

Even though this Is creepy af, I think it works

**Comment by cervonwong** [comment]
Does this work on light mode?

**Comment by octo-kumo** [comment]
<img width="852" alt="Screenshot 2020-12-20 at 8 06 51 PM" src="https://user-images.githubusercontent.com/26460801/102711691-f08f9480-42fe-11eb-9802-8a74bcac5036.png">

looks like it does
